server:
  port: 8080
---

spring:
  profiles: default
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mariadb://localhost:3306/test

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: message
          destination: mileage
          contentType: application/json
        event-out:
          destination: mileage
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8082
---

spring:
  profiles: docker
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mariadb://database-cna.czhhpcsk33j3.ap-southeast-2.rds.amazonaws.com:3306/test

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: message
          destination: mileage
          contentType: application/json
        event-out:
          destination: mileage
          contentType: application/json



#server:
#  port: 8080
#---
#
#spring:
#  profiles: default
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
#        streams:
#          binder:
#            configuration:
#              default:
#                key:
#                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#                value:
#                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#      bindings:
#        event-in:
#          group: message
#          destination: mileage
#          contentType: application/json
#        event-out:
#          destination: mileage
#          contentType: application/json
#
#logging:
#  level:
#    org.hibernate.type: trace
#    org.springframework.cloud: debug
#server:
#  port: 8082
#---
#
#spring:
#  profiles: docker
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: my-kafka.kafka.svc.cluster.local:9092
#        streams:
#          binder:
#            configuration:
#              default:
#                key:
#                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#                value:
#                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#      bindings:
#        event-in:
#          group: message
#          destination: mileage
#          contentType: application/json
#        event-out:
#          destination: mileage
#          contentType: application/json
